<a href="https://colab.research.google.com/github/AlvaroHClaver/teste/blob/main/Untitled11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('/content/flights.csv', dtype={'ORIGIN_AIRPORT': str, 'DESTINATION_AIRPORT': str})
df_reduzido = df.sample(n=100000, random_state=42)
df_reduzido.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
1508570,2015,4,7,2,EV,4900,N759EV,FWA,DTW,1340,...,1423.0,-13.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
363270,2015,1,24,6,AS,611,N413AS,LAS,SEA,1910,...,2133.0,-12.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3003945,2015,7,8,3,WN,1483,N463WN,OAK,SEA,630,...,812.0,-8.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2291425,2015,5,26,2,WN,193,N7745A,STL,DAL,810,...,1222.0,152.0,0,0,NaN,0.0,0.0,0.0,152.0,0.0
2973084,2015,7,6,1,UA,253,N213UA,IAH,HNL,1000,...,1316.0,-2.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#Tratando valores nan
df.fillna(0, inplace=True)
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,0,0.0,0.0,0.0,0.0,0.0
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,0,0.0,0.0,0.0,0.0,0.0
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,0,0.0,0.0,0.0,0.0,0.0
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,0,0.0,0.0,0.0,0.0,0.0
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,0,0.0,0.0,0.0,0.0,0.0

In [12]:
num_rows, num_columns = df.shape
print(f"Quantidade de objetos (linhas): {num_rows}")
print(f"Quantidade de atributos (colunas): {num_columns}")

Quantidade de objetos (linhas): 5819079
Quantidade de atributos (colunas): 31

In [13]:
print("Tipos de dados dos atributos:")
print(df.dtypes)

Tipos de dados dos atributos:
YEAR                     int64
MONTH                    int64
DAY                      int64
DAY_OF_WEEK              int64
AIRLINE                 object
FLIGHT_NUMBER            int64
TAIL_NUMBER             object
ORIGIN_AIRPORT          object
DESTINATION_AIRPORT     object
SCHEDULED_DEPARTURE      int64
DEPARTURE_TIME         float64
DEPARTURE_DELAY        float64
TAXI_OUT               float64
WHEELS_OFF             float64
SCHEDULED_TIME         float64
ELAPSED_TIME           float64
AIR_TIME               float64
DISTANCE                 int64
WHEELS_ON              float64
TAXI_IN                float64
SCHEDULED_ARRIVAL        int64
ARRIVAL_TIME           float64
ARRIVAL_DELAY          float64
DIVERTED                 int64
CANCELLED                int64
CANCELLATION_REASON     object
AIR_SYSTEM_DELAY       float64
SECURITY_DELAY         float64
AIRLINE_DELAY          float64
LATE_AIRCRAFT_DELAY    float64
WEATHER_DELAY          float64
dtype: object

In [14]:
numeric_columns = df.select_dtypes(include=['float64', 'int64']).drop(columns=['year', 'month','arr_flights'], errors='ignore')
print("Resumo estatístico dos atributos numéricos:")
print(numeric_columns.describe())

Resumo estatístico dos atributos numéricos:
            YEAR         MONTH           DAY   DAY_OF_WEEK  FLIGHT_NUMBER  \
count  5819079.0  5.819079e+06  5.819079e+06  5.819079e+06   5.819079e+06
mean      2015.0  6.524085e+00  1.570459e+01  3.926941e+00   2.173093e+03
std          0.0  3.405137e+00  8.783425e+00  1.988845e+00   1.757064e+03
min       2015.0  1.000000e+00  1.000000e+00  1.000000e+00   1.000000e+00
25%       2015.0  4.000000e+00  8.000000e+00  2.000000e+00   7.300000e+02
50%       2015.0  7.000000e+00  1.600000e+01  4.000000e+00   1.690000e+03
75%       2015.0  9.000000e+00  2.300000e+01  6.000000e+00   3.230000e+03
max       2015.0  1.200000e+01  3.100000e+01  7.000000e+00   9.855000e+03

       SCHEDULED_DEPARTURE  DEPARTURE_TIME  DEPARTURE_DELAY      TAXI_OUT  \
count         5.819079e+06    5.732926e+06     5.732926e+06  5.730032e+06
mean          1.329602e+03    1.335204e+03     9.370158e+00  1.607166e+01
std           4.837518e+02    4.964233e+02     3.708094e+01  8.895574e+00
min           1.000000e+00    1.000000e+00    -8.200000e+01  1.000000e+00
25%           9.170000e+02    9.210000e+02    -5.000000e+00  1.100000e+01
50%           1.325000e+03    1.330000e+03    -2.000000e+00  1.400000e+01
75%           1.730000e+03    1.740000e+03     7.000000e+00  1.900000e+01
max           2.359000e+03    2.400000e+03     1.988000e+03  2.250000e+02

         WHEELS_OFF  ...  SCHEDULED_ARRIVAL  ARRIVAL_TIME  ARRIVAL_DELAY  \
count  5.730032e+06  ...       5.819079e+06  5.726566e+06   5.714008e+06
mean   1.357171e+03  ...       1.493808e+03  1.476491e+03   4.407057e+00
std    4.980094e+02  ...       5.071647e+02  5.263197e+02   3.927130e+01
min    1.000000e+00  ...       1.000000e+00  1.000000e+00  -8.700000e+01
25%    9.350000e+02  ...       1.110000e+03  1.059000e+03  -1.300000e+01
50%    1.343000e+03  ...       1.520000e+03  1.512000e+03  -5.000000e+00
75%    1.754000e+03  ...       1.918000e+03  1.917000e+03   8.000000e+00
max    2.400000e+03  ...       2.400000e+03  2.400000e+03   1.971000e+03

           DIVERTED     CANCELLED  AIR_SYSTEM_DELAY  SECURITY_DELAY  \
count  5.819079e+06  5.819079e+06      1.063439e+06    1.063439e+06
mean   2.609863e-03  1.544643e-02      1.348057e+01    7.615387e-02
std    5.102012e-02  1.233201e-01      2.800368e+01    2.143460e+00
min    0.000000e+00  0.000000e+00      0.000000e+00    0.000000e+00
25%    0.000000e+00  0.000000e+00      0.000000e+00    0.000000e+00
50%    0.000000e+00  0.000000e+00      2.000000e+00    0.000000e+00
75%    0.000000e+00  0.000000e+00      1.800000e+01    0.000000e+00
max    1.000000e+00  1.000000e+00      1.134000e+03    5.730000e+02

       AIRLINE_DELAY  LATE_AIRCRAFT_DELAY  WEATHER_DELAY
count   1.063439e+06         1.063439e+06   1.063439e+06
mean    1.896955e+01         2.347284e+01   2.915290e+00
std     4.816164e+01         4.319702e+01   2.043334e+01
min     0.000000e+00         0.000000e+00   0.000000e+00
25%     0.000000e+00         0.000000e+00   0.000000e+00
50%     2.000000e+00         3.000000e+00   0.000000e+00
75%     1.900000e+01         2.900000e+01   0.000000e+00
max     1.971000e+03         1.331000e+03   1.211000e+03

[8 rows x 26 columns]